// <auto-generated />
using System;
using ApiMensageria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMensageria.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221115073808_Mysql")]
    partial class Mysql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiMensageria.Model.LoginModel", b =>
                {
                    b.Property<int>("LoginModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserModelId")
                        .HasColumnType("int");

                    b.HasKey("LoginModelId");

                    b.HasIndex("UserModelId")
                        .IsUnique();

                    b.ToTable("login", (string)null);
                });

            modelBuilder.Entity("ApiMensageria.Model.MessageModel", b =>
                {
                    b.Property<int>("MessageModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Sent")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserIssuerId")
                        .HasColumnType("int");

                    b.Property<int>("UserReceiverId")
                        .HasColumnType("int");

                    b.HasKey("MessageModelId");

                    b.HasIndex("UserIssuerId");

                    b.HasIndex("UserReceiverId");

                    b.ToTable("messagens", (string)null);
                });

            modelBuilder.Entity("ApiMensageria.Model.UserModel", b =>
                {
                    b.Property<int>("UserModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasMaxLength(100)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("LoginModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserModelId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ApiMensageria.Model.LoginModel", b =>
                {
                    b.HasOne("ApiMensageria.Model.UserModel", "User")
                        .WithOne("Login")
                        .HasForeignKey("ApiMensageria.Model.LoginModel", "UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiMensageria.Model.MessageModel", b =>
                {
                    b.HasOne("ApiMensageria.Model.UserModel", "UserIssuer")
                        .WithMany()
                        .HasForeignKey("UserIssuerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiMensageria.Model.UserModel", "UserReceiver")
                        .WithMany("Messages")
                        .HasForeignKey("UserReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserIssuer");

                    b.Navigation("UserReceiver");
                });

            modelBuilder.Entity("ApiMensageria.Model.UserModel", b =>
                {
                    b.Navigation("Login")
                        .IsRequired();

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
